### ISSUE TITLE
Research question too complicated

### ISSUE THREAD

**Issue by firasm** [matthewconnell/547-milestone1#3]
I think the RQ is a bit too complex, they don't know how to do predictions, nor anything about test/train/validation. 

Currently the RQ reads:

> Currently, all 10 prompts in the survey have equal importance in the app’s classification process. Using the same data, are we able to find which (if any) questions are of more significance to determining whether someone has autism spectrum disorder? Are there other variables that are as important or more important to determining a diagnosis?

I suggest something along the lines of:

> What is the relationship between AQ-10 result (cumulative score) and the age of the individual?

That way when they do a linear regression for next week's milestone, it'll answer their question.

**Comment by matthewconnell** [comment]
Thanks for pointing that out, I wasn't sure how complicated to get. 

Addressed with 552866cb893867d47329f3084ab0667ea50977bf
